services:
   segmentio.socket:
         class: Vouchedfor\SegmentIOBundle\Consumer\Socket

    segmentio.segment:
        class: Vouchedfor\SegmentIOBundle\Segment\Segment
        arguments: [% segmentio.socket%, %segmentio.access_token%]
